### PR TITLE
Added Rakuten Front-end.

### PR DESCRIPTION
**Pull request by ogaoga**
Hi Hiro,

I added a link to "Rakuten Front-end" in the portal page.
Could you check and merge it?

Thanks,
Oga

### CODE REVIEW

**Comment by satoryu** [comment]
@hyoshiok Have you checked this pull request? 

@ogaoga 
Thank you for your pull request :exclamation: 
wow, the organization @rakuten-frontend has many repositories! LGTM!
By the way, the branch is conflicting with HEAD of the master. 
Could you please resolve it and push again? 

Thanks,

**Comment by hyoshiok** [comment]
@satoryu No. The pull request was not merged but I merged the change manually. Rakuten Front-end has been included. 

https://github.com/rakutentech/rakutentech.github.io/commit/72c4baeee0e172969af46f06bced7d4fad5475a3

**Comment by satoryu** [comment]
OK :+1:  Please close.

**Comment by ogaoga** [comment]
@satoryu & @hyoshiok , thanks!

**Comment by satoryu** [comment]
:100:

**Pull request closed without merging**
